export const SCHEMA_VERSION = 4;

export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    sku TEXT,
    barcode TEXT,
    category_id TEXT,
    supplier_id TEXT,
    quantity REAL NOT NULL DEFAULT 0,
    min_quantity REAL NOT NULL DEFAULT 0,
    unit TEXT NOT NULL,
    cost_price_cents INTEGER,
    sale_price_cents INTEGER,
    currency TEXT NOT NULL DEFAULT 'BRL',
    expiration_date TEXT,
    batch_code TEXT,
    location TEXT,
    image_uri TEXT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT
  );`,
  `CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);`,
  `CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);`,
  `CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);`,
  `CREATE INDEX IF NOT EXISTS idx_products_supplier_id ON products(supplier_id);`,
  `CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);`,
  `CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);`,
  `CREATE INDEX IF NOT EXISTS idx_products_expiration_date ON products(expiration_date);`,
  `CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    color_token TEXT,
    icon_name TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS suppliers (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    document TEXT,
    address TEXT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS stock_movements (
    id TEXT PRIMARY KEY NOT NULL,
    product_id TEXT NOT NULL,
    type TEXT NOT NULL,
    reason TEXT NOT NULL,
    quantity REAL NOT NULL,
    previous_quantity REAL NOT NULL,
    new_quantity REAL NOT NULL,
    unit_cost_cents INTEGER,
    unit_sale_price_cents INTEGER,
    total_cost_cents INTEGER,
    total_sale_cents INTEGER,
    currency TEXT NOT NULL DEFAULT 'BRL',
    note TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products(id)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id ON stock_movements(product_id);`,
  `CREATE INDEX IF NOT EXISTS idx_stock_movements_created_at ON stock_movements(created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_stock_movements_type ON stock_movements(type);`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    id TEXT PRIMARY KEY NOT NULL,
    theme TEXT NOT NULL DEFAULT 'system',
    language TEXT NOT NULL DEFAULT 'system',
    currency TEXT NOT NULL DEFAULT 'BRL',
    usage_type TEXT NOT NULL DEFAULT 'other',
    app_lock_enabled INTEGER NOT NULL DEFAULT 0,
    biometric_unlock_enabled INTEGER NOT NULL DEFAULT 0,
    hide_financial_values INTEGER NOT NULL DEFAULT 0,
    ads_enabled INTEGER NOT NULL DEFAULT 1,
    personalized_ads_consent TEXT DEFAULT 'unknown',
    expiration_warning_days INTEGER NOT NULL DEFAULT 7,
    low_stock_warning_enabled INTEGER NOT NULL DEFAULT 1,
    expiration_warning_enabled INTEGER NOT NULL DEFAULT 1,
    backup_reminder_enabled INTEGER NOT NULL DEFAULT 0,
    last_backup_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS ad_entitlements (
    id TEXT PRIMARY KEY NOT NULL,
    type TEXT NOT NULL,
    source TEXT NOT NULL,
    feature_key TEXT,
    started_at TEXT NOT NULL,
    expires_at TEXT,
    remaining_uses INTEGER,
    daily_use_date TEXT NOT NULL,
    daily_use_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS feature_usage_limits (
    id TEXT PRIMARY KEY NOT NULL,
    feature_key TEXT NOT NULL,
    date_key TEXT NOT NULL,
    period TEXT NOT NULL,
    used_count INTEGER NOT NULL DEFAULT 0,
    free_limit INTEGER NOT NULL DEFAULT 0,
    rewarded_limit INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    metadata_json TEXT,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS backup_records (
    id TEXT PRIMARY KEY NOT NULL,
    type TEXT NOT NULL,
    format TEXT NOT NULL,
    file_name TEXT,
    file_uri TEXT,
    file_size_bytes INTEGER,
    encrypted INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    error_message TEXT,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS schema_migrations (
    id TEXT PRIMARY KEY NOT NULL,
    version INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL
  );`,
] as const;
